package com.ahmed.clientflow.pdf

import android.content.Context
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.ahmed.clientflow.data.Client
import com.ahmed.clientflow.data.Invoice
import com.ahmed.clientflow.data.Payment
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class InvoicePdfGenerator(private val context: Context) {

    fun generatePdf(invoice: Invoice, client: Client, payment: Payment?): Uri? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas

        val paint = Paint().apply { isAntiAlias = true }
        val titlePaint = Paint().apply {
            isAntiAlias = true
            textSize = 24f
            isFakeBoldText = true
        }
        val headerPaint = Paint().apply {
            isAntiAlias = true
            textSize = 14f
            isFakeBoldText = true
        }
        val textPaint = Paint().apply {
            isAntiAlias = true
            textSize = 12f
        }
        val smallPaint = Paint().apply {
            isAntiAlias = true
            textSize = 10f
        }

        var y = 50f

        // Header - INVOICE
        canvas.drawText("INVOICE", 297f, y, titlePaint)
        y += 30f

        // Invoice number and date
        canvas.drawText("Invoice #: ${invoice.id.take(8).uppercase()}", 40f, y, textPaint)
        canvas.drawText("Date: ${formatDate(invoice.createdAt)}", 400f, y, textPaint)
        y += 25f

        // Status
        val status = when {
            payment == null -> "PENDING"
            payment.status.toString() == "Paid" -> "PAID"
            payment.status.toString() == "Partial" -> "PARTIAL"
            else -> "UNPAID"
        }
        val statusPaint = Paint().apply {
            isAntiAlias = true
            textSize = 12f
            isFakeBoldText = true
            color = when(status) {
                "PAID" -> 0xFF4CAF50.toInt()
                "PARTIAL" -> 0xFFFF9800.toInt()
                else -> 0xFFE53935.toInt()
            }
        }
        canvas.drawText("Status: $status", 40f, y, statusPaint)
        y += 40f

        // Divider
        canvas.drawLine(40f, y, 555f, y, Paint().apply { strokeWidth = 1f })
        y += 20f

        // Client Info
        canvas.drawText("BILL TO:", 40f, y, headerPaint)
        y += 20f
        canvas.drawText(client.name, 40f, y, textPaint)
        y += 18f
        if (client.phone.isNotBlank()) {
            canvas.drawText("Phone: ${client.phone}", 40f, y, textPaint)
            y += 18f
        }
        if (client.serviceType.isNotBlank()) {
            canvas.drawText("Service: ${client.serviceType}", 40f, y, textPaint)
            y += 18f
        }
        y += 20f

        // Divider
        canvas.drawLine(40f, y, 555f, y, Paint().apply { strokeWidth = 1f })
        y += 25f

        // Description header
        canvas.drawText("Description", 40f, y, headerPaint)
        canvas.drawText("Amount", 480f, y, headerPaint)
        y += 20f

        // Divider
        canvas.drawLine(40f, y, 555f, y, Paint().apply { strokeWidth = 0.5f })
        y += 20f

        // Invoice item
        canvas.drawText(invoice.description, 40f, y, textPaint)
        canvas.drawText("$${formatAmount(invoice.amount)}", 480f, y, textPaint)
        y += 25f

        // Divider
        canvas.drawLine(40f, y, 555f, y, Paint().apply { strokeWidth = 1f })
        y += 25f

        // Totals
        if (payment != null) {
            canvas.drawText("Total Amount:", 380f, y, textPaint)
            canvas.drawText("$${formatAmount(payment.totalAmount)}", 480f, y, textPaint)
            y += 20f

            canvas.drawText("Paid Amount:", 380f, y, textPaint)
            canvas.drawText("$${formatAmount(payment.paidAmount)}", 480f, y, textPaint)
            y += 20f

            canvas.drawText("Balance Due:", 380f, y, headerPaint)
            val balance = payment.totalAmount - payment.paidAmount
            canvas.drawText("$${formatAmount(balance)}", 480f, y, headerPaint)
        } else {
            canvas.drawText("Amount Due:", 380f, y, headerPaint)
            canvas.drawText("$${formatAmount(invoice.amount)}", 480f, y, headerPaint)
        }
        y += 40f

        // Footer
        val footerPaint = Paint().apply {
            isAntiAlias = true
            textSize = 10f
            color = 0xFF666666.toInt()
        }
        canvas.drawText("Generated by ClientFlow", 297f, 800f, footerPaint)
        canvas.drawText("Thank you for your business!", 297f, 815f, footerPaint)

        pdfDocument.finishPage(page)

        // Save to file
        val fileName = "invoice_${invoice.id.take(8)}.pdf"
        val file = File(context.cacheDir, fileName)

        return try {
            FileOutputStream(file).use { output ->
                pdfDocument.writeTo(output)
            }
            pdfDocument.close()
            FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    private fun formatDate(timestamp: Long): String {
        return SimpleDateFormat("dd/MM/yyyy", Locale.US).format(Date(timestamp))
    }

    private fun formatAmount(amount: Double): String {
        return if (amount == amount.toLong().toDouble()) "%.0f".format(amount) else "%.2f".format(amount)
    }
}
